```
┌───────────────────────────────────────────────────────────────────────────────┐
│ Projeto Avaliativo Final - Módulo 1                                           │
│ Aluno: Luiz Felipe F. V. Vieira                                               │
└───────────────────────────────────────────────────────────────────────────────┘

┌───────────────────────────────────────────────────────────────────────────────┐
│ Fluxo do Pipeline de dados:                                                   │
│                                                                               │
│ 1- EXTRACT - Verificação e conhecimento da base                               │
│ 2- TRANSFORM - Limpeza dos dados (DUPLICADOS)                                 │
│ 3- TRANSFORM - Correção e tratamento dos dados                                │
│   3.1 -> Correção de tipos (str > datetime)                                   │
│   3.2 -> Conversão e otimização dos tipos de dados                            │
│   3.3 -> Inconsistência de dados                                              │
│   3.4 -> Engenharia de Features                                               │
│ 4. LOAD - Gerar nova base limpa                                               │
│   -> Salvar em um arquivo CSV                                                 │
│   -> Garantir que a AED seja feita na base limpa                              │







│ 6- AED - Gerar estatísticas e análises                       │
│   -> Estatísticas para coluna número de filhos:              │
│      (média; mediana; desvio padrão;                         │
│        moda; máximo; mínimo; contagem)                       │
│   -> Regra de Negócio:                                       │
│      Validar a regra do identificador de número de compra    │
│          -Nota pertence a um único cliente                   │
│          -Nota pertence a um único dia                       │
│   -> Frequência: Quantas notas um mesmo cliente emitiu?      │
│      (Criar 3 grandes grupos)                                │
│   -> Volume de Vendas por Classe Econômica                   │
│   -> Sazonalidades:                                          │
│      - Sazonalidade por Dia da Semana                        │
│      - Sazonalidade Mensal                                   │
│      - Distribuição de Vendas por Período do Mês             │
│   -> Volume de Vendas por Categoria de produtos              │
│                                                              │
├──────────────────────────────────────────────────────────────┤
│                                                              │
│ Para fins didáticos, foram mantidos todos os testes e        │
│ avaliações, mesmo que não resultasse em transformação na     │
│ base de dados.                                               │
│                                                              │
└──────────────────────────────────────────────────────────────┘
```
---

In [256]:

# IMPORTS & CONFIGURAÇÂO

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Leitura do CSV baixado do freeSQL
arquivo_1 = "query_01.csv"
arquivo_2 = "query_02.csv"

df_cargos_depto = pd.read_csv(arquivo_1)
df_localizacao = pd.read_csv(arquivo_2)

print('Bibliotecas e arquivos .csv importados.')

Bibliotecas e arquivos .csv importados.


---

```
┌───────────────────────────────────────────────────────────────────────────────┐
│ 1- EXTRACT - Verificação e conhecimento da base                               │
│   -> df.head(3) / df.tail(3)                                                  │
│   -> df.info()                                                                │
│   -> df.isnull().sum()                                                        │
│   -> df.nunique()                                                             │
└───────────────────────────────────────────────────────────────────────────────┘
```

```
┌───────────────────────────────────────────────────────────────────────────────┐
│ DataFrame Cargos e Departamentos                                              │
└───────────────────────────────────────────────────────────────────────────────┘
```

In [257]:
print('Exibindo as primeiras 3 linhas do DataFrame Cargos e Departamentos.')
df_cargos_depto.head(3)



Exibindo as primeiras 3 linhas do DataFrame Cargos e Departamentos.


,ID,DATA_CONTRATACAO,SALARIO,COMISSAO,DEPARTAMENTO,CARGO,CARGO_SALARIO_MIN,CARGO_SALARIO_MAX
0,100,2013-06-17T00:00:00Z,24000,NaN,Executive,President,20080,40000
1,101,2015-09-21T00:00:00Z,17000,NaN,Executive,Administration Vice President,15000,30000
2,102,2011-01-13T00:00:00Z,17000,NaN,Executive,Administration Vice President,15000,30000


In [258]:
print('Exibindo as Últimas 3 linhas do DataFrame Cargos e Departamentos.')
df_cargos_depto.tail(3)



Exibindo as Últimas 3 linhas do DataFrame Cargos e Departamentos.


,ID,DATA_CONTRATACAO,SALARIO,COMISSAO,DEPARTAMENTO,CARGO,CARGO_SALARIO_MIN,CARGO_SALARIO_MAX
104,204,2012-06-07T00:00:00Z,10000,NaN,Public Relations,Public Relations Representative,4500,10500
105,205,2012-06-07T00:00:00Z,12008,NaN,Accounting,Accounting Manager,8200,16000
106,206,2012-06-07T00:00:00Z,8300,NaN,Accounting,Public Accountant,4200,9000


In [259]:
print('Exibindo número de registros, colunas, valores não nulos e tipo de dados.')
df_cargos_depto.info()



Exibindo número de registros, colunas, valores não nulos e tipo de dados.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ID                 107 non-null    int64  
 1   DATA_CONTRATACAO   107 non-null    object 
 2   SALARIO            107 non-null    int64  
 3   COMISSAO           35 non-null     float64
 4   DEPARTAMENTO       106 non-null    object 
 5   CARGO              107 non-null    object 
 6   CARGO_SALARIO_MIN  107 non-null    int64  
 7   CARGO_SALARIO_MAX  107 non-null    int64  
dtypes: float64(1), int64(4), object(3)
memory usage: 6.8+ KB


In [260]:
print('Exibindo número de registros nulos em cada coluna.')
df_cargos_depto.isnull().sum()     



Exibindo número de registros nulos em cada coluna.


ID                    0
DATA_CONTRATACAO      0
SALARIO               0
COMISSAO             72
DEPARTAMENTO          1
CARGO                 0
CARGO_SALARIO_MIN     0
CARGO_SALARIO_MAX     0
dtype: int64

In [261]:
print('Contando o número de registros únicos em cada coluna')
df_cargos_depto.nunique()



Contando o número de registros únicos em cada coluna


ID                   107
DATA_CONTRATACAO      98
SALARIO               58
COMISSAO               7
DEPARTAMENTO          11
CARGO                 19
CARGO_SALARIO_MIN     14
CARGO_SALARIO_MAX     13
dtype: int64

```
┌───────────────────────────────────────────────────────────────────────────────┐
│ DataFrame Localização (Distribuição Geográfica)                               │
└───────────────────────────────────────────────────────────────────────────────┘
```

In [262]:
print('Exibindo as primeiras 3 linhas do DataFrame Localização.')
df_localizacao.head(3)



Exibindo as primeiras 3 linhas do DataFrame Localização.


,ID,DATA_CONTRATACAO,SALARIO,COMISSAO,DEPARTAMENTO,CIDADE,ESTADO,PAIS,REGIAO
0,202,2015-08-17T00:00:00Z,6000,NaN,Marketing,Toronto,Ontario,Canada,Americas
1,201,2014-02-17T00:00:00Z,13000,NaN,Marketing,Toronto,Ontario,Canada,Americas
2,205,2012-06-07T00:00:00Z,12008,NaN,Accounting,Seattle,Washington,United States of America,Americas


In [263]:
print('Exibindo as Últimas 3 linhas do DataFrame Localicação.')
df_localizacao.tail(3)



Exibindo as Últimas 3 linhas do DataFrame Localicação.


,ID,DATA_CONTRATACAO,SALARIO,COMISSAO,DEPARTAMENTO,CIDADE,ESTADO,PAIS,REGIAO
104,146,2015-01-05T00:00:00Z,13500,0.30,Sales,Oxford,Oxford,United Kingdom of Great Britain and Northern I...,Europe
105,145,2014-10-01T00:00:00Z,14000,0.40,Sales,Oxford,Oxford,United Kingdom of Great Britain and Northern I...,Europe
106,178,2017-05-24T00:00:00Z,7000,0.15,NaN,NaN,NaN,NaN,NaN


In [264]:
print('Exibindo número de registros, colunas, valores não nulos e tipo de dados.')
df_localizacao.info()



Exibindo número de registros, colunas, valores não nulos e tipo de dados.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                107 non-null    int64  
 1   DATA_CONTRATACAO  107 non-null    object 
 2   SALARIO           107 non-null    int64  
 3   COMISSAO          35 non-null     float64
 4   DEPARTAMENTO      106 non-null    object 
 5   CIDADE            106 non-null    object 
 6   ESTADO            105 non-null    object 
 7   PAIS              106 non-null    object 
 8   REGIAO            106 non-null    object 
dtypes: float64(1), int64(2), object(6)
memory usage: 7.7+ KB


In [265]:
print('Exibindo número de registros nulos em cada coluna.')
df_localizacao.isnull().sum()   



Exibindo número de registros nulos em cada coluna.


ID                   0
DATA_CONTRATACAO     0
SALARIO              0
COMISSAO            72
DEPARTAMENTO         1
CIDADE               1
ESTADO               2
PAIS                 1
REGIAO               1
dtype: int64

In [266]:
print('Contando o número de registros únicos em cada coluna')
df_localizacao.nunique()



Contando o número de registros únicos em cada coluna


ID                  107
DATA_CONTRATACAO     98
SALARIO              58
COMISSAO              7
DEPARTAMENTO         11
CIDADE                7
ESTADO                6
PAIS                  4
REGIAO                2
dtype: int64

---

```
┌───────────────────────────────────────────────────────────────────────────────┐
│ 2- TRANSFORM -  Limpeza dos dados [DUPLICADOS]                                │
└───────────────────────────────────────────────────────────────────────────────┘
```

In [267]:
#############################################################
# DataFrame Cargos e Departamentos
# Exibindo total linhas, únicas e duplicadas
# Objetivo: mostrar quantos registros seriam perdidos 
# ao aplicar drop_duplicates().
#############################################################

total_linhas = len(df_cargos_depto)
linhas_unicas = len(df_cargos_depto.drop_duplicates())
duplicadas = total_linhas - linhas_unicas

print('Mostrando o impacto da remoção dos duplicados no DF Cargos e Departamentos:')    
print(f'Total de linhas: {total_linhas:,}')
print(f'Linhas únicas: {linhas_unicas:,}')
print(f'Linhas duplicadas: {duplicadas:,}')
print(f'Percentual removido: {(duplicadas/total_linhas)*100:.2f}%')

Mostrando o impacto da remoção dos duplicados no DF Cargos e Departamentos:
Total de linhas: 107
Linhas únicas: 107
Linhas duplicadas: 0
Percentual removido: 0.00%


In [268]:
#############################################################
# DataFrame Localização
# Exibindo total linhas, únicas e duplicadas
# Objetivo: mostrar quantos registros seriam perdidos 
# ao aplicar drop_duplicates().
#############################################################

total_linhas = len(df_localizacao)
linhas_unicas = len(df_localizacao.drop_duplicates())
duplicadas = total_linhas - linhas_unicas

print('Mostrando o impacto da remoção dos duplicados no DF Localização:')    
print(f'Total de linhas: {total_linhas:,}')
print(f'Linhas únicas: {linhas_unicas:,}')
print(f'Linhas duplicadas: {duplicadas:,}')
print(f'Percentual removido: {(duplicadas/total_linhas)*100:.2f}%')

Mostrando o impacto da remoção dos duplicados no DF Localização:
Total de linhas: 107
Linhas únicas: 107
Linhas duplicadas: 0
Percentual removido: 0.00%




**CONCLUSÃO:**

-> Não existem linhas duplicadas em nenhum dos dataframes


---
```
┌───────────────────────────────────────────────────────────────────────────────┐
│ 3- TRANSFORM - Correção e tratamento dos dados                                │
│   3.1 -> Correção de tipos (str > datetime)                                   │
│   3.2 -> Conversão e otimização dos tipos de dados                            │
│   3.3 -> Inconsistência de dados                                              │
│   3.4 -> Engenharia de Features                                               │
└───────────────────────────────────────────────────────────────────────────────┘
```

```
┌───────────────────────────────────────────────────────────────────────────────┐
│   -> Fazer uma cópia dos DataFrames para preservar o original                 │
│   e iniciar a transformação dos dados                                         │
└───────────────────────────────────────────────────────────────────────────────┘
```

In [269]:
df_depto_limpo = df_cargos_depto.copy()
df_localizacao_limpo = df_localizacao.copy()


```
┌───────────────────────────────────────────────────────────────────────────────┐
│   3.1 -> Correção de tipos (str > datetime)                                   │
└───────────────────────────────────────────────────────────────────────────────┘
```

In [270]:
#############################################################    
# Converter coluna DATA_CONTRATACAO (str) para datetime
#############################################################    

df_depto_limpo['DATA_CONTRATACAO'] = pd.to_datetime(df_depto_limpo['DATA_CONTRATACAO'], errors='coerce')

print('===== DataFrame Cargos e Departamentos =====')
print('Coluna DATA_CONTRATACAO transformada no tipo datetime com sucesso!')
print(f'Novo tipo de dado da coluna DATA_CONTRATACAO: {df_depto_limpo['DATA_CONTRATACAO'].dtype}')

df_localizacao_limpo['DATA_CONTRATACAO'] = pd.to_datetime(df_localizacao_limpo['DATA_CONTRATACAO'], errors='coerce')

print('\n\n===== DataFrame Localização =====')
print('Coluna DATA_CONTRATACAO transformada no tipo datetime com sucesso!')
print(f'Novo tipo de dado da coluna DATA_CONTRATACAO: {df_localizacao_limpo['DATA_CONTRATACAO'].dtype}')


===== DataFrame Cargos e Departamentos =====
Coluna DATA_CONTRATACAO transformada no tipo datetime com sucesso!
Novo tipo de dado da coluna DATA_CONTRATACAO: datetime64[ns, UTC]


===== DataFrame Localização =====
Coluna DATA_CONTRATACAO transformada no tipo datetime com sucesso!
Novo tipo de dado da coluna DATA_CONTRATACAO: datetime64[ns, UTC]


In [271]:
#############################################################    
# Inconsistência de dados -> Data: Válida ou NaT?
# Objetivo: Validar coluna de Data
#############################################################    

datas_invalidas = df_depto_limpo['DATA_CONTRATACAO'].isna().sum()
print(f'Linhas com Datas inválidas (DataFrame Cargos Departamentos): {datas_invalidas}')


datas_invalidas = df_localizacao_limpo['DATA_CONTRATACAO'].isna().sum()
print(f'Linhas com Datas inválidas (DataFrame Localização): {datas_invalidas}')



Linhas com Datas inválidas (DataFrame Cargos Departamentos): 0
Linhas com Datas inválidas (DataFrame Localização): 0


```
┌───────────────────────────────────────────────────────────────────────────────┐
│   3.2 -> Conversão e otimização dos tipos de dados                            │
└───────────────────────────────────────────────────────────────────────────────┘
```

Realizar a adequação dos tipos de dados das colunas visando reduzir o consumo de memória e melhorar a eficiência das operações analíticas.

Colunas categóricas -> Converter de str para o tipo category

Colunas numéricas -> Ajustar para tipo mais compacto (int16 e int32)

In [272]:
#############################################################    
# Conversão de dados:
# Tabela df_depto_limpo (Cargos e Departamentos)
# Após análise dos dados no item 1 (conhecimento da base)
#############################################################    


# Conversão das colunas para os novos tipos
df_depto_limpo['ID'] = df_depto_limpo['ID'].astype('int16')
df_depto_limpo['SALARIO'] = df_depto_limpo['SALARIO'].astype('int32')
df_depto_limpo['DEPARTAMENTO'] = df_depto_limpo['DEPARTAMENTO'].astype('category')
df_depto_limpo['CARGO'] = df_depto_limpo['CARGO'].astype('category')
df_depto_limpo['CARGO_SALARIO_MIN'] = df_depto_limpo['CARGO_SALARIO_MIN'].astype('int32')
df_depto_limpo['CARGO_SALARIO_MAX'] = df_depto_limpo['CARGO_SALARIO_MAX'].astype('int32')

print('Mostrando o nome da coluna e seu respectivo tipo de dado transformado:')
print(df_depto_limpo.dtypes)   


Mostrando o nome da coluna e seu respectivo tipo de dado transformado:
ID                                 int16
DATA_CONTRATACAO     datetime64[ns, UTC]
SALARIO                            int32
COMISSAO                         float64
DEPARTAMENTO                    category
CARGO                           category
CARGO_SALARIO_MIN                  int32
CARGO_SALARIO_MAX                  int32
dtype: object


In [273]:
#############################################################    
# Conversão de dados:
# Tabela df_localizacao_limpo (Localização)
# Após análise dos dados no item 1 (conhecimento da base)
#############################################################    


# Conversão das colunas do tipo "int"
df_localizacao_limpo['ID'] = df_localizacao_limpo['ID'].astype('int16')
df_localizacao_limpo['SALARIO'] = df_localizacao_limpo['SALARIO'].astype('int32')

# Conversão das colunas de Categoria
categorias = [
    'DEPARTAMENTO',
    'CIDADE',
    'ESTADO',
    'PAIS',
    'REGIAO'    
]

for col in categorias:
    df_localizacao_limpo[col] = df_localizacao_limpo[col].astype('category')

print('Mostrando o nome da coluna e seu respectivo tipo de dado transformado:')
print(df_localizacao_limpo.dtypes)   


Mostrando o nome da coluna e seu respectivo tipo de dado transformado:
ID                                int16
DATA_CONTRATACAO    datetime64[ns, UTC]
SALARIO                           int32
COMISSAO                        float64
DEPARTAMENTO                   category
CIDADE                         category
ESTADO                         category
PAIS                           category
REGIAO                         category
dtype: object


```
┌───────────────────────────────────────────────────────────────────────────────┐
│   3.3 -> Inconsistência de dados                                              │
└───────────────────────────────────────────────────────────────────────────────┘
```

Realizar a verificação de consistência de dados nas colunas categoricas.

Fazer o tratamento das linhas com valores nulos.


##### ========== DataFrame Cargos e Departamentos ==========


In [274]:
#############################################################     
# DataFrame Cargos e Departamentos
# Objetivo: Validar colunas categorica 'DEPARTAMENTO'
#############################################################    

print('\n===== Valores encontrados na coluna DEPARTAMENTO =====\n')
print(df_depto_limpo['DEPARTAMENTO'].value_counts(dropna=False))



===== Valores encontrados na coluna DEPARTAMENTO =====

DEPARTAMENTO
Shipping            45
Sales               34
Finance              6
Purchasing           6
IT                   5
Executive            3
Marketing            2
Accounting           2
Administration       1
Human Resources      1
Public Relations     1
NaN                  1
Name: count, dtype: int64


In [275]:
#############################################################     
# DataFrame Cargos e Departamentos
# Objetivo: Validar colunas categorica 'CARGO'
############################################################# 

print('\n\n===== Valores encontrados na coluna CARGO =====\n')
print(df_depto_limpo['CARGO'].value_counts(dropna=False))



===== Valores encontrados na coluna CARGO =====

CARGO
Sales Representative               30
Shipping Clerk                     20
Stock Clerk                        20
Purchasing Clerk                    5
Sales Manager                       5
Accountant                          5
Programmer                          5
Stock Manager                       5
Administration Vice President       2
Administration Assistant            1
Accounting Manager                  1
Public Accountant                   1
President                           1
Marketing Representative            1
Marketing Manager                   1
Finance Manager                     1
Human Resources Representative      1
Purchasing Manager                  1
Public Relations Representative     1
Name: count, dtype: int64


**CONCLUSÃO:**

-> DEPARTAMENTO com  "NaN" (vazio) com 1 registro (**Necessário investigação**)

In [276]:
#############################################################   
# Verificação de todo o registro da linha encontrada
# com DEPARTAMENTO = NaN
#############################################################   

print('\nVisualizando linha com DEPARTAMENTO "NaN"\n')
print(df_depto_limpo[df_depto_limpo['DEPARTAMENTO'].isna()].to_string(index=False))   




Visualizando linha com DEPARTAMENTO "NaN"

 ID          DATA_CONTRATACAO  SALARIO  COMISSAO DEPARTAMENTO                CARGO  CARGO_SALARIO_MIN  CARGO_SALARIO_MAX
178 2017-05-24 00:00:00+00:00     7000      0.15          NaN Sales Representative               6000              12008


**CONCLUSÃO:**

-> A linha com DEPARTAMENTO sem valor tem o ID = 178

-> A mesma linha tem como cargo "Sales Representative", vamos investigar nos outros registros a qual departamento pertence este cargo.

In [277]:
#############################################################   
# Vamos contar em cada departamento, 
# quantos CARGO = 'Sales Representative' possuem
#############################################################   

count_departamentos = df_depto_limpo[df_depto_limpo['CARGO'] == 'Sales Representative']['DEPARTAMENTO'].value_counts(dropna=False)

print('\nVisualizando departamentos com CARGO = "Sales Representative"\n')
print(count_departamentos[count_departamentos >= 1])   




Visualizando departamentos com CARGO = "Sales Representative"

DEPARTAMENTO
Sales    29
NaN       1
Name: count, dtype: int64


**CONCLUSÃO:**

-> Todos os outros registros que possuem o cargo 'Sales Representative' estão no departamento 'Sales'. Então podemos corrigir este registro e atribuir o mesmo departamento para que não fique vazio.

In [278]:
#############################################################   
# Corrigindo o registro com o método .loc
# como temos apenas 1 linha com DEPARTAMENTO = NaN
# filtraremos por essa linha
#############################################################   

df_depto_limpo.loc[df_depto_limpo['DEPARTAMENTO'].isna(), 'DEPARTAMENTO'] = 'Sales'   

# Verificamos anteriormente que a linha tinha o ID = 178, Vamos validar se o Departamento foi corrigido
print(df_depto_limpo[df_depto_limpo['ID'] == 178].to_string(index=False))



 ID          DATA_CONTRATACAO  SALARIO  COMISSAO DEPARTAMENTO                CARGO  CARGO_SALARIO_MIN  CARGO_SALARIO_MAX
178 2017-05-24 00:00:00+00:00     7000      0.15        Sales Sales Representative               6000              12008



<br>

##### =============== DataFrame Localização ===============

<br>

In [279]:
#############################################################     
# DataFrame Localização
# Objetivo: Validar colunas categoricas 
# DEPARTAMENTO, CIDADE, ESTADO, PAIS e REGIAO
#############################################################    

print('\n===== Valores encontrados na coluna DEPARTAMENTO =====')
print(df_localizacao_limpo['DEPARTAMENTO'].value_counts(dropna=False))




===== Valores encontrados na coluna DEPARTAMENTO =====
DEPARTAMENTO
Shipping            45
Sales               34
Finance              6
Purchasing           6
IT                   5
Executive            3
Marketing            2
Accounting           2
Administration       1
Human Resources      1
Public Relations     1
NaN                  1
Name: count, dtype: int64


In [280]:

print('\n\n===== Valores encontrados na coluna CIDADE =====')
print(df_localizacao_limpo['CIDADE'].value_counts(dropna=False))





===== Valores encontrados na coluna CIDADE =====
CIDADE
South San Francisco    45
Oxford                 34
Seattle                18
Southlake               5
Toronto                 2
Munich                  1
London                  1
NaN                     1
Name: count, dtype: int64


In [281]:

print('\n\n===== Valores encontrados na coluna ESTADO =====')
print(df_localizacao_limpo['ESTADO'].value_counts(dropna=False))





===== Valores encontrados na coluna ESTADO =====
ESTADO
California    45
Oxford        34
Washington    18
Texas          5
Ontario        2
NaN            2
Bavaria        1
Name: count, dtype: int64


In [282]:

print('\n\n===== Valores encontrados na coluna PAIS =====')
print(df_localizacao_limpo['PAIS'].value_counts(dropna=False))





===== Valores encontrados na coluna PAIS =====
PAIS
United States of America                                68
United Kingdom of Great Britain and Northern Ireland    35
Canada                                                   2
Germany                                                  1
NaN                                                      1
Name: count, dtype: int64


In [283]:

print('\n\n===== Valores encontrados na coluna REGIAO =====')
print(df_localizacao_limpo['REGIAO'].value_counts(dropna=False))





===== Valores encontrados na coluna REGIAO =====
REGIAO
Americas    70
Europe      36
NaN          1
Name: count, dtype: int64


**CONCLUSÃO:**

-> Nas colunas DEPARTAMENTO, CIDADE, PAIS e REGIAO existe um registro vazio (NaN)

-> Na coluna ESTADO existem 2 registros vazios (NaN) 

-> Os outros valores parecem corretos.

-> (**Necessário investigação**)

In [284]:
#############################################################   
# Verificação de todos os registros que possuem NaN
# em qualquer uma das 5 colunas
#############################################################   

colunas_alvo = ['DEPARTAMENTO', 'CIDADE', 'ESTADO', 'PAIS', 'REGIAO']

# Filtra linhas onde pelo menos uma das colunas listadas é NaN
# '.any(axis=1)' = Verifica, linha por linha (axis=1), se algum valor é True 
# (ou seja, se há pelo menos um NaN nessas colunas)

df_nan = df_localizacao_limpo[df_localizacao_limpo[colunas_alvo].isna().any(axis=1)]

print(df_nan.to_string(index=False))



 ID          DATA_CONTRATACAO  SALARIO  COMISSAO    DEPARTAMENTO CIDADE ESTADO                                                 PAIS REGIAO
203 2012-06-07 00:00:00+00:00     6500       NaN Human Resources London    NaN United Kingdom of Great Britain and Northern Ireland Europe
178 2017-05-24 00:00:00+00:00     7000      0.15             NaN    NaN    NaN                                                  NaN    NaN


**CONCLUSÃO:**

-> Foram retornadas 2 linhas que possuem pelo menos uma coluna categórica vazias (NaN).

-> O primeiro registro, com ID = 203 tem apenas a coluna ESTADO vazia. Verificando nas análizes anteriores podemos ver que temos 35 registro no PAIS 'United Kingdom of Great Britain and Northern Ireland', vamos investigar este PAIS para descobrir como podemos preencher a coluna ESTADO.

-> O segundo registro, com ID = 178 é o mesmo caso do outro DataFrame onde a coluna DEPARTAMENTO está vazia. Na nossa query para extração dos dados (LEFT JOIN) a Localização é relacionada ao Departamento, por isso todas as colunas de localização vieram vazias. Vamos investigar se o Departamento 'Sales' (onde descobrimos que o ID 178 pertence) consta na mesma localização em todos os registros. 

```sql
(LEFT JOIN HR.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID)
```

In [285]:

#############################################################   
# Investigação para o ID = 203
# Verificar o pais 'United Kingdom of Great Britain and Northern Ireland'
#############################################################   

# Verificar quais cidades pertence a esse país e quantas vezes aparecem

count_cidades = df_localizacao_limpo[df_localizacao_limpo['PAIS'] == 'United Kingdom of Great Britain and Northern Ireland']['CIDADE'].value_counts()
print('Contagem de cidades no pais:')
print(count_cidades[count_cidades >= 1])

# Encontramos na investigação anterior que além de 'London' todas as outras cidades são 'Oxford'
# Verificar qual estado pertence 'Oxford' e a integridade se todos os registros constam lá

count_estados = df_localizacao_limpo[df_localizacao_limpo['CIDADE'] == 'Oxford']['ESTADO'].value_counts()
print('\nA cidade de Oxford pertence ao estado:')
print(count_estados[count_estados >= 1])



Contagem de cidades no pais:
CIDADE
Oxford    34
London     1
Name: count, dtype: int64

A cidade de Oxford pertence ao estado:
ESTADO
Oxford    34
Name: count, dtype: int64


**CONCLUSÃO:**

No País pesquisado 34 cidades tem o registro de 'Oxford' e estão no ESTADO 'Oxford'. Desta forma sobrou somente a CIDADE 'London' sem ESTADO. Para que o registro não fique vazio para análise, podemos preencher o estado também como 'London'.

In [286]:

#############################################################   
# Correção para o ID = 203
# Preencher o ESTADO como 'London'
#############################################################  

# Como transformamos a coluna em categoria, 
# é necessário adicionar a Categoria 'London' para não dar erro
df_localizacao_limpo['ESTADO'] = df_localizacao_limpo['ESTADO'].cat.add_categories(['London'])

# Corrigindo o registro com o método .loc
df_localizacao_limpo.loc[df_localizacao_limpo['ID'] == 203, 'ESTADO'] = 'London'   

# Validando o ID 203 foi modificado
print(df_localizacao_limpo[df_localizacao_limpo['ID'] == 203].to_string(index=False))



 ID          DATA_CONTRATACAO  SALARIO  COMISSAO    DEPARTAMENTO CIDADE ESTADO                                                 PAIS REGIAO
203 2012-06-07 00:00:00+00:00     6500       NaN Human Resources London London United Kingdom of Great Britain and Northern Ireland Europe


In [287]:

#############################################################   
# Investigação para o ID = 178
# Verificar nos outros registros a Localização de 'Sales'
#############################################################   

colunas_alvo = ['CIDADE', 'ESTADO', 'PAIS', 'REGIAO']

# Contar para cada coluna alvo, qual registro existe filtrando pelo depto 'Sales'

count_localizacao = df_localizacao_limpo[df_localizacao_limpo['DEPARTAMENTO'] == 'Sales'][colunas_alvo].value_counts()
print('Contagem de Localizações:')
print(count_localizacao)




Contagem de Localizações:
CIDADE  ESTADO  PAIS                                                  REGIAO
Oxford  Oxford  United Kingdom of Great Britain and Northern Ireland  Europe    34
Name: count, dtype: int64


**CONCLUSÃO:**

Todos os registros com DEPARTAMENTO = 'Sales' estão na mesma localização, então podemos preencher a mesma informação no ID 178, pois como verificamos antes, este funcionário também faz parte do departamento Sales.

In [288]:

#############################################################   
# Correção para o ID = 178
# Preencher DEPARTAMENTO com 'Sales'
# Preencher dados de Localização do departamento Sales
#############################################################   

# Corrigindo o registro com o método .loc
df_localizacao_limpo.loc[df_localizacao_limpo['ID'] == 178, ['DEPARTAMENTO', 'CIDADE', 'ESTADO', 'PAIS', 'REGIAO']] = ['Sales', 'Oxford', 'Oxford', 'United Kingdom of Great Britain and Northern Ireland', 'Europe']   

# Validação do preenchimento
print(df_localizacao_limpo[df_localizacao_limpo['ID'] == 178].to_string(index=False))

 ID          DATA_CONTRATACAO  SALARIO  COMISSAO DEPARTAMENTO CIDADE ESTADO                                                 PAIS REGIAO
178 2017-05-24 00:00:00+00:00     7000      0.15        Sales Oxford Oxford United Kingdom of Great Britain and Northern Ireland Europe



```
┌───────────────────────────────────────────────────────────────────────────────┐
│   3.4 -> Engenharia de Features                                               │
└───────────────────────────────────────────────────────────────────────────────┘
```

In [289]:
#############################################################    
# Engenharia de Features -> Features temporais
# Objetivo: Criar features temporaris para análises por período
#############################################################   

# Criação de Dia, Mês e Ano

df_depto_limpo['DIA'] = df_depto_limpo['DATA_CONTRATACAO'].dt.day
df_depto_limpo['MES'] = df_depto_limpo['DATA_CONTRATACAO'].dt.month
df_depto_limpo['ANO'] = df_depto_limpo['DATA_CONTRATACAO'].dt.year

print('\n 3 Novas colunas criadas. Mostrando todas as colunas da base:\n')
print(df_depto_limpo.columns.to_list())




 3 Novas colunas criadas. Mostrando todas as colunas da base:

['ID', 'DATA_CONTRATACAO', 'SALARIO', 'COMISSAO', 'DEPARTAMENTO', 'CARGO', 'CARGO_SALARIO_MIN', 'CARGO_SALARIO_MAX', 'DIA', 'MES', 'ANO']


---

```
┌───────────────────────────────────────────────────────────────────────────────┐
│ 4. LOAD - Gerar nova base limpa                                               │
│   -> Salvar em um arquivo CSV                                                 │
│   -> Garantir que a AED seja feita na base limpa                              │
└───────────────────────────────────────────────────────────────────────────────┘
```

Para completar o fluxo de ETL (Extract - Transform - Load) agora precisamos gera a nova base final (fonte única da verdade).

Como importamos duas tabelas através das duas querys mas ambas vieram da mesma tabela fato (HR.EMPLOYEES) da base HR (Human Resources), vamos mesclá-las transformando em uma única base limpa e garantir que toda a AED seja feita nela.

Para garantir a persistência destes dados, esta nova tabela será salva como um novo arquivo .csv

In [290]:

#############################################################    
# Load -> Salvar CSV
# Objetivo: Salvar o DataFrame limpo e enriquecido
# Antes de salvar, vamos mesclar as tabelas com o método pd.merge()
#############################################################   

# Selecionar as colunas da tabela df_localizacao_limpo
colunas_selecionadas = ['ID', 'CIDADE', 'ESTADO', 'PAIS', 'REGIAO']
df_localizacao_merge = df_localizacao_limpo[colunas_selecionadas]

# pd.merge()
# on='ID': define a coluna como chave para união
# how='outer': mantém todas as linhas das duas (nossas tabelas tem as mesmas linhas)
df_final = pd.merge(df_depto_limpo, df_localizacao_merge, on='ID', how='outer')


# salvar csv
nome_csv = 'base_final.csv'
df_final.to_csv(
    nome_csv,
    index=False,    # não salva o índice numérico como coluna extra
    sep=';'         # separador ponto-e-vírgula
)

print('Salvando DataFrame Limpo em CSV:')
print(f'✓ {nome_csv} salvo com sucesso!')
print(f'Colunas finais: {df_final.columns.tolist()}')
print(f'Linhas        : {len(df_final)}')



Salvando DataFrame Limpo em CSV:
✓ base_final.csv salvo com sucesso!
Colunas finais: ['ID', 'DATA_CONTRATACAO', 'SALARIO', 'COMISSAO', 'DEPARTAMENTO', 'CARGO', 'CARGO_SALARIO_MIN', 'CARGO_SALARIO_MAX', 'DIA', 'MES', 'ANO', 'CIDADE', 'ESTADO', 'PAIS', 'REGIAO']
Linhas        : 107
