SELECT
    E.EMPLOYEE_ID AS id,
    E.HIRE_DATE AS data_contratacao,
    E.SALARY AS salario,
    E.COMMISSION_PCT AS comissao,
    D.DEPARTMENT_NAME AS departamento,
    L.CITY AS cidade,
    L.STATE_PROVINCE AS estado,
    C.COUNTRY_NAME AS pais,
    R.REGION_NAME AS regiao
FROM HR.EMPLOYEES E
LEFT JOIN HR.DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
LEFT JOIN HR.COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID
LEFT JOIN HR.REGIONS R
    ON C.REGION_ID = R.REGION_ID
WHERE  E.SALARY IS NOT NULL
    AND E.SALARY > 0
ORDER BY R.REGION_NAME, C.COUNTRY_NAME, L.CITY;